[package]
name = "raft-common"
version.workspace = true
edition.workspace = true


build = "build.rs"


[dependencies]
protobuf = { version = "3.4.0" }
heed = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
log = { workspace = true }
